### ISSUE TITLE
Unable to update stat for player

### ISSUE THREAD

**Issue by Ste3et** [ajgeiss0702/ajLeaderboards#14]
ajLeaderboards try to save a player with color to database.

I can't find any kind of User starts with Se, on my server it is impossible that the playername can bee changed.
In the stacktrace i can't find the real playername who the plugin try to save, maybe you can give me an info what i can change.

https://paste.gg/p/anonymous/6e7aa45d0f734e9286a5761900cc234a

Greetings
Ste3et_C0st

**Comment by Ste3et** [comment]
Ah ok it try to save the player with Suffix/Prefix to the database

**Comment by ajgeiss0702** [comment]
This is not the place to get support
