### ISSUE TITLE
ajleaderboards lock contention causes server save to take ~5 seconds

### ISSUE THREAD

**Issue by dbechrd** [ajgeiss0702/ajLeaderboards#15]
Our server auto-saves every 10 minutes. ajLeaderboards seems to have a bug that causes saves to take a solid 5 seconds, which results in massive TPS lag while saving. It's something to do with `TopManager.reload()`.

https://github.com/ajgeiss0702/ajLeaderboards/blob/master/src/main/java/us/ajg0702/leaderboards/boards/TopManager.java#L143

Here's the full stack trace during the hang:

![image](https://user-images.githubusercontent.com/707367/227696454-f77b7984-a369-4bff-91a6-b4d667126994.png)
![image](https://user-images.githubusercontent.com/707367/227696486-1a25d6c7-ffc9-482f-90c6-1990f3f4d62f.png)

**Comment by ajgeiss0702** [comment]
This is not the place to get support

**Comment by dbechrd** [comment]
That's a very rude and unprofessional response to a rather serious issue I put a fair bit of effort into diagnosing and reporting.

Perhaps you could also bother to mention where the "place to get support is", if not a Github issue.

My bad for submitting something via the most commonly used forum for reporting issues in open source projects. -_-

**Comment by ajgeiss0702** [comment]
From my end, it doesn’t appear that you put much effort into reporting the issue. It says multiple times on the plugin page and on the wiki where the best places to get support are, yet you simply clicked the first link on the plugin page without bothering to look under the giant banner that says support.

I’m sorry that I have not added a note here that this is not the place to get support (I actually started looking into that as soon as I closed this issue), however in the future when trying to get support, at least read the plugin page a little bit to see where the best place to get support is

**Comment by dbechrd** [comment]
I have no idea what plugin page or red banner you're referring to. I came here by googling "ajleaderboards github" after seeing the stack trace I linked above. I'm diagnosing an issue for a friend's server and have no idea where they got the plugin itself from. It would be helpful if this repo had a README with relevant info if you want people to go elsewhere. I'm much more of a developer than a Minecraft server admin so I went to the first place any dev would have thought of. I'm not sure where normal users go, but my intent was just to report a bug more so than looking for end-user support.

**Comment by dbechrd** [comment]
Also, if you're not aware, you can turn off "Issues" in your repo settings on Github. If you don't want to receive messages this way, that might help redirect people to the right place (e.g. via the README).

**Comment by ajgeiss0702** [comment]
As I said before, I have not implemented an issue template with a warning.

This hasn’t been much of an issue before, as most people actually read the stuff I provide to help.

I don’t want to completely disable issues so they can still be used for discussion of development

**Comment by ajgeiss0702** [comment]
If you want to discuss this more, please contact me using one of the normal methods for support. Additionally, then I could also help you resolve your issue ;)
