### ISSUE TITLE
dont-add-zero options still adds values that are zero to the leaderboard

### ISSUE THREAD

**Issue by peber7** [ajgeiss0702/ajLeaderboards#16]
note "player_edr" is a custom placeholder that actually works

I tried the following in the config:
    dont-add-zero: [player_edr]
    dont-add-zero: ["player_edr"]
However, the values that return zero from the placeholder are still being added to the leaderboards.

I checked out the source code and I think the issue may be that there isn't a return statement if the condition is true.

Thanks!

![Screenshot 2023-04-04 181625](https://user-images.githubusercontent.com/97802425/229934836-d9da45e2-af28-4828-82c2-476fe298d74e.png)

**Comment by ajgeiss0702** [comment]
This is not the place to get support
