### ISSUE TITLE
If a player leaves the server too quickly, his statistics do not change.

### ISSUE THREAD

**Issue by Regomy** [ajgeiss0702/ajLeaderboards#19]
What do I mean? Player 1metse on the balance, he creates a twink, throws there all the money and immediately out, as a result, he remains in the top, but it adds more and his twin, if the player who gave the money comes - the top will be updated, but he does not go. And it turns out that 1 player with accounts player_1 player_2 engaged all the top, and with the same balance.

**Comment by ajgeiss0702** [comment]
This is not the place to get support
