### ISSUE TITLE
itemsadder prefixes dont work

### ISSUE THREAD

**Issue by Medved0546** [ajgeiss0702/ajLeaderboards#26]
itemsadder prefixes dont work in %ajlb_lb_statistic_deaths_1_alltime_prefix% (in all tops)
but in the usual holograms %img_player% work correctly

decentholograms ajleaderboards placeholderapi itemsadder latest stable versions
paper 1.16.5
java 17 (Temurin-17.0.8.1+1 from Eclipse Adoptium)

![javaw_EtegvEnieB](https://github.com/ajgeiss0702/ajLeaderboards/assets/140727790/038c9018-7d85-4c54-a9e2-c02ac2ebb42d)

cfg ajlb + dh
[Desktop.zip](https://github.com/ajgeiss0702/ajLeaderboards/files/12885908/Desktop.zip)

**Comment by ajgeiss0702** [comment]
this is not the place to get support
