### ISSUE TITLE
Feature request: import / export boards to yml files

### ISSUE THREAD

**Issue by svaningelgem** [ajgeiss0702/ajLeaderboards#32]
I know there is the import & export command. But these import / export data.
I know there is the webviewer... But that's also just showing the data in a fancier way.

What I'm looking for is a way to configure the boards via a yml file and load them into ajLeaderboards.
And export the ones we have.

This would make for MUCH more easy configuration as with the chat and the huge strings, it gets very tedious...

I'm thinking of something like: `/ajlb board import|export <filename>` and then the configuration will get written to that file in the datafolder.

**Comment by ajgeiss0702** [comment]
This is not the place for feature requests.

Also, you said you already know about the import/export commands, then proceed to request basically exactly what the import/export commands do??

Please use one of the normal ways to contact me
