### ISSUE TITLE
Custom URL for processing skins

### ISSUE THREAD

**Issue by luckyway7** [ajgeiss0702/ajLeaderboards#33]
I suggest adding in the config for your own URL for processing skins
![2024-08-17_19-18](https://github.com/user-attachments/assets/08e1b8eb-0417-4079-8974-2ea203cca8cf)

The given URL is showing wrong and old skins, I want to use my URL instead. Now I have to decompile the plugin and compile it again to change it to my URL. Is it possible to put this in the config?

**Comment by ajgeiss0702** [comment]
this is not the place to get support
